sudo: required
dist: trusty

addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk

install: echo "skip bundle install"

branches:
  only:
  - master

services: docker

env:
  global:
  - RUBYOPT="-W0"
  matrix:
  - CHEF_VERSION=current INSTANCE=default-ubuntu-1404

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef gem install kitchen-docker
- "/opt/chefdk/bin/chef exec rake tests"

script:
- KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

notifications:
  slack:
    secure:
    on_failure: change
    on_success: change
    rooms:
      secure: bUqC6r1Xep1cc+j2VNn4FOdo9g0U8/fujp6A7P58+bP76JwhxCNXyEhJfiyKmWTkclqnQnyL2GdHbKP7lZ4aRCBBJ37OsRTtndxn4CbsL2lNHPU6DXwQMzvgfOm69OeUAXwaf3l40dtOdKBasvyLflSf5EdS/1p6S1wIz6UMPZPch7lro1YPFfXa8uazFDIN798z/UcuSN4dYyow5gPSdB4D4ys1eOJEqqW+WENeapxHsUdViDkun1oc9DHi8Ro91gQIXh4vL2++V4l4W7+zxHItboXF5lCiiTBRX+FJ4MUUU+yWoQ81JBBt38hkkf4ZbaUuGkI4wgf/KOU9hxzFO20Hefy2qwMva/nhxpeUy28BauSLdWo38xao5hqkCYX61kCCNnXr6WLIhdMtKOJABKNRj4K9y0frUfDM2bl6maL/1O9SDmghzCdFbj8JvOlPyDxPvXjOjL5ej1iIJ5r8qvykIvTVx1JexVsvvkjGIMT5minftK6gl60+8hlfE1I0C1eUKxA/VNRIg2ntD+WAZQlItbYmuYXi2Zm7iupuzMTnF0TDXwhIPSiW3TKBRyKPJXhSLOAtyXETMSwjcPmAboaR4nEtKkGAKdWO1sIDDnaatibhwyrIw4SLKeN9cK9/DLFiw5SZxVJQQsjk83+GLx4KLLjidl1yAGFS0eaPAII=
  email:
    on_success: change
    on_failure: always
